/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface Arrow {
    'NotArrowImage': string;
    'UndefinedArrowImage': string;
    'arrowImage': string;
    'arrowId': string;
    'orientation'?: 'top' | 'bottom' | 'right' | 'left';
    'reasonTitle': string;
    'reasonsPosition'?: 'top' | 'bottom' | 'right' | 'left' | 'auto';
    'reasonsTrigger'?: 'click' | 'hover' | 'focus' | 'manual';
    'visible': boolean;
  }
}

declare global {


  interface HTMLArrowElement extends Components.Arrow, HTMLStencilElement {}
  var HTMLArrowElement: {
    prototype: HTMLArrowElement;
    new (): HTMLArrowElement;
  };
  interface HTMLElementTagNameMap {
    'arrow': HTMLArrowElement;
  }
}

declare namespace LocalJSX {
  interface Arrow extends JSXBase.HTMLAttributes<HTMLArrowElement> {
    'NotArrowImage': string;
    'UndefinedArrowImage': string;
    'arrowImage': string;
    'arrowId': string;
    'orientation'?: 'top' | 'bottom' | 'right' | 'left';
    'reasonTitle': string;
    'reasonsPosition'?: 'top' | 'bottom' | 'right' | 'left' | 'auto';
    'reasonsTrigger'?: 'click' | 'hover' | 'focus' | 'manual';
    'visible': boolean;
  }

  interface IntrinsicElements {
    'arrow': Arrow;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


