/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ArrowComponent {
    'RedArrowImage': string;
    'UndefinedArrowImage': string;
    'arrowId': string;
    'arrowImage': string;
    'orientation'?: 'top' | 'bottom' | 'right' | 'left';
    'reasonsPosition'?: 'top' | 'bottom' | 'right' | 'left' | 'auto';
    'reasonsTrigger'?: 'click' | 'hover' | 'focus' | 'manual';
    'visible': boolean;
  }
}

declare global {


  interface HTMLArrowComponentElement extends Components.ArrowComponent, HTMLStencilElement {}
  var HTMLArrowComponentElement: {
    prototype: HTMLArrowComponentElement;
    new (): HTMLArrowComponentElement;
  };
  interface HTMLElementTagNameMap {
    'arrow-component': HTMLArrowComponentElement;
  }
}

declare namespace LocalJSX {
  interface ArrowComponent extends JSXBase.HTMLAttributes<HTMLArrowComponentElement> {
    'RedArrowImage'?: string;
    'UndefinedArrowImage'?: string;
    'arrowId'?: string;
    'arrowImage'?: string;
    'orientation'?: 'top' | 'bottom' | 'right' | 'left';
    'reasonsPosition'?: 'top' | 'bottom' | 'right' | 'left' | 'auto';
    'reasonsTrigger'?: 'click' | 'hover' | 'focus' | 'manual';
    'visible'?: boolean;
  }

  interface IntrinsicElements {
    'arrow-component': ArrowComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


